server:
  port: 9000


# ???????????
#spring:
#  web:
#    resources:
#      cache:
#        period: 6000
#        cachecontrol:
#          max-age: 7000
#        use-last-modified: true
##        ?????????????
#      static-locations: classpath:/static_resources
#  mvc:
##    ??????????????
#    static-path-pattern: /static/**


# ?????????
spring:
  mvc:
    contentnegotiation:
      favor-parameter: true
      parameter-name: type
      # ???????
      media-types:
        yaml: text/yaml
